### ISSUE TITLE
Transformations that can't be generated by Quartz

### ISSUE THREAD

**Issue by RosaryXiang** [quantum-compiler/quartz#115]
There is a circuit:
"CNOT": [2, 1],"CNOT": [0, 3],"CNOT": [1, 3],"RZ": [3, "theta_1"],"CNOT": [1, 3],"CNOT": [2, 3],"RZ": [3, "theta_2"],"CNOT": [0, 3],"RZ": [3, "theta_3"],"CNOT": [1, 3],"RZ": [3, "theta_4"]
The representative of the ECC this circuit belongs to is:
"CNOT": [2, 3],"RZ": [3, "theta_3"],"CNOT": [0, 3],"RZ": [3, "theta_2"],"CNOT": [1, 3],"RZ": [1, "theta_1"],"CNOT": [0, 3],"CNOT": [2, 3],"RZ": [3, "theta_4"],"CNOT": [2, 1]

however, there is another circuit:
"CNOT": [2, 1],"CNOT": [0, 3],"CNOT": [1, 3],"RZ": [3, "theta_1"],"CNOT": [1, 3],"CNOT": [2, 3],"RZ": [3, "theta_2"],"CNOT": [0, 3],"RZ": [3, "theta_3"],"CNOT": [1, 3],"RZ": [3, "theta_4"],"CNOT": [2, 3],"CNOT": [1, 3]
The representative of the ECC this circuit belongs to is:
"CNOT": [2, 3],"RZ": [3, "theta_3"],"CNOT": [0, 3],"RZ": [3, "theta_2"],"CNOT": [1, 3],"RZ": [3, "theta_1"],"CNOT": [0, 3],"CNOT": [2, 3],"RZ": [3, "theta_4"],"CNOT": [1, 3],"CNOT": [2, 1]

see? They are too different transformations, however, the second transformation cannot be generated by Quartz, due to the limitation that Quartz generates dags from representatives. Is this an imperfection of Quartz, or I misunderstand? I would really appreciate it if you could clear me up.

**Comment by xumingkuan** [comment]
Hi @RosaryXiang, thanks for asking! First, I would assume `"RZ": [1, "theta_1"]` in the first representative is actually `"RZ": [3, "theta_1"]` to be consistent with the prefix of the second one.

One important thing to note is Quartz only generates ECC sets that *subsume* all transformations, instead of directly including all transformations. A set including all transformations (thus including all possible circuits) will be very large, as you may have noticed that the representative set can be much larger than the ECC set with the same parameters generated by `gen_ecc_set.cpp`, not to mention a set including all possible circuits which will be much larger than the representative set. ECC sets are compact representations such that some transformations are split into several transformations in the ECC set.

In your example, there should be a transformation in the ECC set that is equivalent to the following *under certain qubit permutations*:
`"CNOT": [2, 1],"CNOT": [2, 3],"CNOT": [1, 3] = "CNOT": [1, 3],"CNOT": [2, 1]`

(or, `"CNOT": [2, 3],"CNOT": [1, 3] = "CNOT": [2, 1],"CNOT": [1, 3],"CNOT": [2, 1]` with `"CNOT": [2, 1],"CNOT": [2, 1] = (empty)`)

For the "another circuit" in your example, we can first replace the prefix with the representative in the ECC to get
`"CNOT": [2, 3],"RZ": [3, "theta_3"],"CNOT": [0, 3],"RZ": [3, "theta_2"],"CNOT": [1, 3],"RZ": [3, "theta_1"],"CNOT": [0, 3],"CNOT": [2, 3],"RZ": [3, "theta_4"],"CNOT": [2, 1],"CNOT": [2, 3],"CNOT": [1, 3]`

Then we can apply the transformation above to get the desired circuit
`"CNOT": [2, 3],"RZ": [3, "theta_3"],"CNOT": [0, 3],"RZ": [3, "theta_2"],"CNOT": [1, 3],"RZ": [3, "theta_1"],"CNOT": [0, 3],"CNOT": [2, 3],"RZ": [3, "theta_4"],"CNOT": [1, 3],"CNOT": [2, 1]`.

**Comment by xumingkuan** [comment]
Please let me know if there is anything unclear with my explanation or I'll close this issue soon.

**Comment by RosaryXiang** [comment]
Thank you for your explanation, which is very clear and there is no ambiguity. I'm so sorry. I could have answered you earlier. Please close this issue.

> Please let me know if there is anything unclear with my explanation or I'll close this issue soon.
