### ISSUE TITLE
`run_ibmq.sh` doesn't generate compiled files

### ISSUE THREAD

**Issue by vtomole** [quantum-compiler/quartz#129]
The way I understand it [run_ibmq.sh](https://github.com/quantum-compiler/quartz/blob/master/run_ibmq.sh) is supposed to compile the circuits in `circuit/nam-benchmarks/` and put the compiled circuits in `circuit/nam-benchmarks/output`. When I run said script, that's not what happens. The script builds the binary and successfully exits without compiling the circuits. 

```
vtomole@vtomole:~/quartz$ ./run_ibmq.sh 
[ 91%] Built target quartz_runtime
[100%] Built target test_ibmq
vtomole@vtomole:~/quartz$ ls circuit/nam-benchmarks/outuput
ls: cannot access 'circuit/nam-benchmarks/outuput': No such file or directory
```

When I try to compile each circuit individually the program segfaults

```
./run_ibmq.sh: line 38: 93150 Segmentation fault      ./test_ibmq ../circuit/nam-benchmarks/gf2^9_mult.qasm --output ../circuit/nam-benchmarks/output_files/rigetti/gf2^9_mult.qasm.output.rigetti $eqset_arg
```

What am I missing?

**Comment by xumingkuan** [comment]
Hi! Thanks for your interest in Quartz. Sorry that the scripts here are not well-organized. The corresponding script in the Artifact repo (https://github.com/quantum-compiler/quartz-artifact/blob/main/run_ibmq.sh) has an extra line to create the output folder `mkdir -p ../circuit/nam-benchmarks/output_files/ibmq`. The program segfaulted because we did not have that line in the script here and the output folder did not exist.

I have updated the scripts just now so please pull the repo if you would like to run Quartz through the scripts. Note that the scripts are mainly for experiment purposes to run a bunch of circuits conveniently when we're developing Quartz. It is recommended to write C++ code like https://github.com/quantum-compiler/quartz/blob/master/src/test/test_quartz.cpp to optimize one circuit.

**Comment by vtomole** [comment]
> Running test_quartz.cpp aborts

Oh, I needed to pass in the circuit. ` ./test_quartz hello.qasm` works. :+1:

**Comment by xumingkuan** [comment]
I also got `Segmentation fault (core dumped)` when I ran `test_ibmq` just now... But `./run_nam.sh` or `test_nam` works.

@zikun-li Do you have any quick thoughts on the issue about `test_ibmq`?

**Comment by xumingkuan** [comment]
Just confirmed that on v0.1.1, `run_ibmq.sh` works when `IBM_4_3_complete_ECC_set.json` exists in Quartz's root folder. You can find the ECC set at https://zenodo.org/records/6508992, or you can generate the ECC set on your own. The ECC set is large so we did not put it on GitHub.

On the master branch, please generate the ECC set first by modifying `gen_ecc_set.cpp` and running it before running `run_ibmq.sh`.
