### ISSUE TITLE
Rotation Parameterization

### ISSUE THREAD

**Issue by ScottWe** [quantum-compiler/quartz#190]
I think that there might be an issue with the parameterization of OpenQASM rotations. In the OpenQASM specifications (see [here](https://arxiv.org/pdf/2104.14722) and [here](https://learning.quantum.ibm.com/tutorial/explore-gates-and-circuits-with-the-quantum-composer)), the P-rotation (for some Pauli-matrix P) is defined to be $\exp(-i ( \theta / 2 ) P)$. However, the P-rotations in Quartz seem to be implemented as $\exp(i \theta P)$. When circuits do not have constant parameters, I guess this isn't an issue, since the gate sets are equivalent up to a linear reparameterization. However, this would cause issues with constant parameters.

For example, the following block of code will identify the circuits as belonging to different equivalence classes. When `pi` is replaced with `pi/2`, they appear in the same equivalence class.
```
#include "quartz/context/context.h"
#include "quartz/dataset/dataset.h"
#include "quartz/gate/gate.h"
#include "quartz/parser/qasm_parser.h"

using namespace quartz;

int main(int argc, char **argv) {
  ParamInfo param_info(0);
  Context ctx({ GateType::x, GateType::s, GateType::rx, GateType::pi }, &param_info);

  QASMParser parser(&ctx);
  parser.use_symbolic_pi(true);
  
  std::string str1 = "OPENQASM 2.0;\n"
                    "include \"qelib1.inc\";\n"
                    "qubit[1] q;\n"
                    "x q[0];\n";
  
  std::string str2 = "OPENQASM 2.0;\n"
                    "include \"qelib1.inc\";\n"
                    "qubit[1] q;\n"
                    "rx(pi) q[0];\n"
                    "s q[0];\n"
                    "x q[0];\n"
                    "s q[0];\n"
                    "x q[0];\n";
  
  CircuitSeq *circ1 = nullptr;
  CircuitSeq *circ2 = nullptr;
  parser.load_qasm_str(str1, circ1);
  parser.load_qasm_str(str2, circ2);

  Dataset data;
  data.insert(&ctx, std::unique_ptr<CircuitSeq>(circ1));
  data.insert(&ctx, std::unique_ptr<CircuitSeq>(circ2));

  data.save_json(&ctx, "tmp.json");
  return 0;
}
```
However, they implement the same gate (this [snippet](https://quantum.ibm.com/composer/files/new?initial=N4IgdghgtgpiBcICqYAuBLVAbGATABAMboBOhArpiADQgCOEAzlAiAPIAKAogHICKAQQDKAWXwAmAHQAGANwAdMOjCEs5XDHzz6MLOgBGARknLC2hWEV0SMAOb46AbUMBdCyQAeACgAO6AJQOjtJuioxBIRYeEaFg4U6RitEJsTQgGoyEJOg%2BGAD2YKwgAL5AA) shows that `rx(pi) q[0]; s q[0]; x q[0]; s  q[0]; x q[0]` is an `x` gate in OpenQASM 2).

At first I was going to make a pull request to fix this. However, there seems to be many solutions, and I wasn't sure which of those solutions the maintainers would prefer.

**Comment by xumingkuan** [comment]
Thanks for bringing this issue up. Indeed, when Quartz was built at the beginning, some gates like `RZ` and `RX` were purposely implemented with half of the angle parameter. This is because it then avoids halving the angles in the verifier (which is a problem because we do not know the sign of the sin/cos values) and it does not change anything when we only use symbolic parameters.

$$
RZ(\theta/2) = \begin{pmatrix} e^{-i\theta/2} & 0 \\
0 & e^{i\theta/2} \end{pmatrix}
$$

Note that other gates that do P-rotation like `P` and `U1` gates do not have this issue:

$$
P(\theta) = U1(\theta) = \begin{pmatrix} 1 & 0 \\
0 & e^{i\theta} \end{pmatrix}
$$

However, this feature might be forgotten when we implemented the QASM parser. I personally prefer still storing $\theta/2$ in the gate, letting the QASM parser divide the constant parameter by 2 when we load the circuit, and multiplying the constant parameter by 2 when we print the circuit. We can have a virtual function `virtual bool is_param_halved(int param_id) const;` like `virtual bool is_sparse() const;` or `virtual bool is_diagonal() const;` in `gate.h` to specify if the `param_id`-th parameter is halved if it is a constant parameter. We would need this argument `param_id` because in U3 gates, only the 0-th parameter $\theta$ is halved.

**Comment by ScottWe** [comment]
This makes sense. To reiterating, you're suggesting this right?

- Each gate will have a new piece of metadata which identifies parameters with a period of $4 * \pi$.
- When the parser encounters such a gate, it will read the expression $\theta$, and then set the parameter to $\theta / 2$.
- When a circuit is converted from a dag to OpenQASM, if such a gate is encountered, then the parameter is scaled by 2.

I played around with this a bit, but I did run into one issue. I think this program illustrates it well enough.
```
OPENQASM 3;
include "stdgates.inc"

input array[angle, 2] p;
qubit[1] q;

rx(pi + p[0]) q[0];
p(p[1]) q[0];
```
Since this program mixes together both `rx` and `p`, then it is necessary to rescale one of the symbolic parameters. The obvious choice would be to divide `p[0]` by `2`, though this would require the half-angle formula. I'm hesitant to implement this, since this would lead to square roots of symbolic parameters ,which Z3 often struggles with. Another option is to rescale `p[1]` by `2`, though I think this would lead to many other complications.

Do you have any thoughts on this case?

**An Aside**

For the evaluation I want to carry out, I just need support for `rx`, `ry`, and `rz`. If you decide that supporting the above example is too complicated, then I'm happy to implement a partial solution.

**Comment by xumingkuan** [comment]
> - Each gate will have a new piece of metadata which identifies parameters with a period of $4 * \pi$.

This is not quite accurate: in the gate

$$
RZ(\theta/2) = \begin{pmatrix} e^{-i\theta/2} & 0 \\
0 & e^{i\theta/2} \end{pmatrix},
$$

the parameter is $\theta/2$ instead of $\theta$, so all parameters will have a period of $2 * \pi$. Here $\theta/2$ has a period of $2 * \pi$. The original gate $RZ(\theta)$ does have a period of $4 * \pi$, but Quartz does not store this original gate.

> ```
> rx(pi + p[0]) q[0];
> p(p[1]) q[0];
> ```

Good catch! I didn't think about this case.

> this would lead to square roots of symbolic parameters ,which Z3 often struggles with

This is true.

What about this solution:
- When creating symbolic parameters, add an option to specify if it is going to be used in any `rx, ry, rz` gates. Suppose `p[0]` has this option turned on, and we will only store the symbolic parameter `p[0]/2`. In `ParamInfo`, we can have a vector `std::vector<bool> is_parameter_halved_;` similar to `std::vector<bool> is_parameter_symbolic_;`.
- When an `rx, ry, rz` uses a symbolic parameter, we assert that the parameter is halved.
- When an `rx, ry, rz` uses a parameter expression with all symbolic parameters, we assert that all parameters used are halved.
- When an `rx, ry, rz` uses a parameter expression mixing symbolic and constant parameters, feel free to implement a partial solution and assert unimplemented for unsupported cases.
- When other gates directly or indirectly use a halved symbolic parameter, use the doubled gate instead. We may want to cache a parameter expression `p[0]/2 + p[0]/2` for each halved symbolic parameter `p[0]/2`.
- How do we set this option for each symbolic parameter? I think one fast way to do this is to conservatively turn this option on for each symbolic gate *if the context contains any gates like `rx, ry, rz`*. Note that `ParamParser` has a pointer to the `Context` so we know this.
